### ISSUE TITLE
JumpSeat Travel No results found

### ISSUE THREAD

**Issue by northway** [FatihKoz/DisposableBasic#17] opened 2024-01-06 11:26 UTC
Hi!

After updating the Disposable Basic module, the JumpSeat Travel widget doesn't list any airports.

Can you help us find what's broke?

- PHP version: 8.1
- phpVMS version: 7.0.0-beta.5+230828.61433c
- Disposable Basic version: v3.5.7

**Comment by FatihKoz** [comment] 2024-01-06 12:41
Hi,

Possible causes;

* Javascript cross origin errors (CORS) caused by wrong `.env` definitions. 
  _check browser console and your `APP_URL` in `.env`, be sure it starts with `https` if you are using SSL and don't forget cleaning application cache._
* Faulty `app.blade.php` to support recent changes required for ajax powered dropdowns.
  _needs updated theme, including duplicates you have like your own theme_
* Faulty `jumpseat.blade.php` to support recent changes required for ajax powered dropdowns.
  _original release is working fine, check any duplicated blades you have or your custom changes_

Hope the above helps or gives you some clues to figure out the error and fix.

I am 100% sure that DispoBasic and JumpSeat travel widget is fully compatible with ajax powered dropdowns and working fine, thus closing this issue.

**Closed by FatihKoz** 2024-01-06 12:41 UTC

**Comment by northway** [comment] 2024-01-06 13:25
Thank you for the pointers!

The `app.blade.php` in our theme contained and outdated JS code.

Now, everything works as intended!

**Comment by FatihKoz** [comment] 2024-01-06 15:23
Great news 😉
